version: "3"
services:
  react-app:
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
    networks:
      - post-me

  backend-api:
    build: ./backend/
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - post-me

  mongo:
    image: mongo:4.2.6
    ports:
      - "27017:27017"
    networks:
      - post-me
    volumes:
      - mongo-data:/data/db

networks:
  post-me:
    driver: bridge

volumes:
  mongo-data:
    driver: local
